version: "3"
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - cache:/data
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db:/var/lib/mysql
  api:
    container_name: online-bookstore
    image: online-bookstore-api
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mysql

volumes:
  db:
    driver: local
  cache:
    driver: local